on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
        - run: |
              pip install galgebra scipy
              python build.py
              git add -A
              git config user.name dummy
              git config user.email dummy
              git commit --allow-empty-message -m ''
              git push
