on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
        - run: |
              pip install sympy scipy gitpython
              python rayleigh/main.py
              python build.py
